(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];let timer=null,toastTimer;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),3500)}
function stop(){clearInterval(timer);timer=null;$('#play-route').textContent='播放七日路线';$('#play-route').setAttribute('aria-pressed','false')}
function selectDay(n,manual=true){if(manual)stop();$$('[data-map-day]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.mapDay)===n)));$$('[data-segment]').forEach(p=>{p.classList.toggle('dim',n!==0&&Number(p.dataset.segment)!==n);p.classList.toggle('lit',n!==0&&Number(p.dataset.segment)===n)});$$('[data-flight]').forEach(p=>p.classList.toggle('dim',n!==0&&Number(p.dataset.flight)!==n));const d=$('#day-'+n);$('#route-label').textContent=d?d.dataset.date+' '+$('.day-title p',d).textContent:'汉中往返，自驾与航空双线衔接';$('#route-summary-title').textContent=d?$('.day-title h3',d).textContent:'以额济纳为核心，不把每天排满';$('#route-summary-copy').textContent=d?$('.day-aside .keep',d).textContent:'丹霞、胡杨与沙坡头是三个重点。额济纳连住两晚，最后一晚住中卫，顺路返程。';$('#route-detail').href=d?'#day-'+n:'#itinerary';$('#route-detail').textContent=d?'展开当日安排':'查看完整七日日程';if(window.tripFoodSelect)window.tripFoodSelect(n)}
$$('[data-map-day]').forEach(b=>b.addEventListener('click',()=>selectDay(Number(b.dataset.mapDay))));$('#play-route').addEventListener('click',()=>{if(timer){stop();return}let n=1;selectDay(n,false);$('#play-route').textContent='停止播放';$('#play-route').setAttribute('aria-pressed','true');timer=setInterval(()=>{if(++n>7){stop();return}selectDay(n,false)},1800)});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});document.addEventListener('keydown',e=>{if(e.key==='Escape')stop()});
$('#expand-all').addEventListener('click',()=>$$('.day-card').forEach(d=>d.open=true));$('#collapse-all').addEventListener('click',()=>$$('.day-card').forEach(d=>d.open=false));document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#day-"]');if(a){const d=$(a.getAttribute('href'));if(d)d.open=true}});if(/^#day-[1-7]$/.test(location.hash)){const d=$(location.hash);d.open=true;setTimeout(()=>d.scrollIntoView(),100)}
function fmt(m){m=Math.round(m);let pre='';if(m<0){pre='前一日 ';m=((m%1440)+1440)%1440}return pre+String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
function calculate(){
 const t=$('#flight-time').value,start=$('#planned-start').value;
 const v=['drive-hours','rest-hours','road-buffer','airport-buffer'].map(id=>Number($('#'+id).value));
 if(!/^\d{2}:\d{2}$/.test(t)||!/^\d{2}:\d{2}$/.test(start)||v.some(x=>!Number.isFinite(x)||x<0)||v[0]<1||v[0]>24||v[1]>8||v[2]>8||v[3]<1||v[3]>6){$('#calc-time').textContent='检查输入';$('#calc-text').textContent='请填写有效的航班、离开景区时间及驾驶、休息和机场预留。';return}
 const [h,m]=t.split(':').map(Number),[sh,sm]=start.split(':').map(Number);
 const flight=h*60+m,planned=sh*60+sm,road=v[0]+v[1]+v[2],latest=flight-(road+v[3])*60,arrival=flight-v[3]*60;
 $('#calc-time').textContent=fmt(latest);
 const diff=planned-latest;
 $('#calc-text').textContent='按当前输入，须不晚于'+fmt(latest)+'离开居延海，'+fmt(arrival)+'前抵达机场。'+(diff>0?'计划'+start+'离开，比倒排时刻晚'+Math.floor(diff/60)+'小时'+String(Math.round(diff%60)).padStart(2,'0')+'分；取消居延海或另行调整返京安排。':'计划'+start+'离开在倒排范围内，仍须复核实际高德路线、休息和实时路况。')+' 纯驾驶默认10小时为演示预算，不是高德结果。';
 $('#calc-time').classList.toggle('risk',diff>0);
}
$$('.calc input').forEach(i=>i.addEventListener('input',calculate));calculate();
const key='northwest-autumn-2026-checklist-v1';let stored={},storageOK=true;try{stored=JSON.parse(localStorage.getItem(key)||'{}')||{}}catch(_){storageOK=false}$$('[data-check]').forEach(i=>i.checked=stored[i.dataset.check]===true);
function updateChecks(write=false){const c=$$('[data-check]'),n=c.filter(i=>i.checked).length;$('#check-count').textContent='已准备 '+n+' / '+c.length;$('#check-progress').style.width=n/c.length*100+'%';$('#check-progress-wrap').setAttribute('aria-valuenow',n);if(write)try{localStorage.setItem(key,JSON.stringify(Object.fromEntries(c.map(i=>[i.dataset.check,i.checked]))))}catch(_){storageOK=false}$('#check-local-note').textContent=storageOK?'勾选仅保存在当前浏览器，不上传，也不会与其他设备自动同步。':'当前环境无法持久保存勾选；本次页面内仍可正常使用清单。'}
$$('[data-check]').forEach(i=>i.addEventListener('change',()=>updateChecks(true)));updateChecks();$('#reset-checks').addEventListener('click',()=>{if(!confirm('清空当前浏览器保存的行前准备勾选？'))return;$$('[data-check]').forEach(i=>i.checked=false);updateChecks(true);toast('行前清单已清空')});
function download(text,name,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function markdown(){
 let s='# 西北秋行｜2026国庆七日自驾总体计划\n\n日期：2026年10月1日至7日。版本：2026-09-29。全部时刻为北京时间。\n\n';
 s+='## 路线与当前状态\n\n汉中 → 武威 → 张掖七彩丹霞 → 嘉峪关 → 额济纳 → 居延海〔有条件〕→ 银川 → 中卫沙坡头 → 汉中。\n\n10月2日21:15计划抵达嘉峪关。10月5日MU6262已购票，公开常规班表列21:40银川起飞、次日00:05到北京大兴；电子客票上的时刻及北京到达机场须核对。航天参观待预约，10月3日发射与可参加观礼均未确认。\n\n';
 $$('.day-card').forEach(d=>{const n=Number(d.id.replace('day-',''));s+='## '+d.dataset.date+' '+d.dataset.weekday+'｜'+$('.day-title h3',d).textContent+'\n\n';if(window.tripDayOverviewMarkdown)s+=window.tripDayOverviewMarkdown(n);s+=$('.day-intro',d).textContent+'\n\n';$$('.time-slot',d).forEach(e=>s+='### '+$('time',e).textContent+'｜'+$('h4',e).textContent+'\n\n'+$('p',e).textContent+'\n\n');$$('.day-aside>div',d).forEach(e=>s+='**'+$('h4',e).textContent+'：**'+$('p',e).textContent+'\n\n');s+='注意：'+$('.day-note',d).textContent+'\n\n';if(window.tripFoodDayMarkdown)s+=window.tripFoodDayMarkdown(n);if(window.tripStayDayMarkdown)s+=window.tripStayDayMarkdown(n);if(window.tripRoadDayMarkdown)s+=window.tripRoadDayMarkdown(n)});
 s+='## 返京日时间倒排\n\n居延海附近10月5日晨光约06:48，日出约07:16。08:30离开居延海只是意向，需先核对能否在19:10前抵达银川河东机场。若不能，取消日出支线，直接从额济纳前往机场。\n\n最晚离开居延海 = 起飞时间 − 高德实测纯驾驶时间 − 正常休息用餐 − 道路缓冲 − 机场预留。页面演示值不代表高德结果，也不保证赶机。\n\n';
 s+='## 行前准备\n\n';$$('.check-row span').forEach(e=>s+='- [ ] '+e.textContent+'\n');
 s+='\n## 资料与核验边界\n\n- [MU6262公开常规班表](https://flights.ctrip.com/international/Schedule/INC-BJS.html)：不是指定日期电子客票。\n- [居延海附近2026-10-05日出](https://aa.usno.navy.mil/api/rstt/oneday?date=2026-10-05&coords=42.33354,101.243935&tz=8)：美国海军天文台按近似坐标计算。\n- [高德路线规划](https://ditu.amap.com/dir)：需按实际地点核对。\n';
 if(window.tripRoadMarkdown)s+=window.tripRoadMarkdown();if(window.tripStayMarkdown)s+=window.tripStayMarkdown();if(window.tripFoodMarkdown)s+=window.tripFoodMarkdown();return s
}
$('#download-plan').addEventListener('click',()=>{if(!window.tripFoodReady){toast('美食资料仍在加载，请稍后导出；加载失败时刷新页面。');return}download(markdown(),'西北秋行_七日总体计划_2026.md','text/markdown;charset=utf-8');toast('总体计划已导出为Markdown')});
let printStates=[];window.addEventListener('beforeprint',()=>{printStates=$$('.day-card').map(d=>d.open);$$('.day-card').forEach(d=>d.open=true)});window.addEventListener('afterprint',()=>$$('.day-card').forEach((d,i)=>d.open=printStates[i]??true));$('#print-plan').addEventListener('click',()=>window.print());
$('#share').addEventListener('click',async()=>{const url='https://chastelover.github.io/xinjiang-yili-roadtrip/northwest-autumn-2026/';try{if(navigator.share){await navigator.share({title:'西北秋行｜国庆七日旅行手册',text:'河西走廊、额济纳胡杨与沙坡头，7天6晚。',url});return}if(navigator.clipboard&&isSecureContext){await navigator.clipboard.writeText(url);toast('在线网页地址已复制');return}prompt('复制网页地址后分享；离线版可直接分享HTML文件。',url)}catch(e){if(e.name!=='AbortError')prompt('复制以下网页地址分享：',url)}});
if('IntersectionObserver' in window){const o=new IntersectionObserver(entries=>{for(const e of entries){if(!e.isIntersecting)continue;$$('.navlinks a,.mobile-nav a').forEach(a=>{const on=a.getAttribute('href')==='#'+e.target.id;a.classList.toggle('active',on);if(on)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}},{rootMargin:'-12% 0px -68% 0px',threshold:0});$$('main>section[id]').forEach(s=>o.observe(s))}selectDay(0);window.tripExportMarkdown=markdown;
// Keep the base handbook usable even if the optional food module cannot load.
if(!window.tripFoodReady){const food=document.createElement('script');food.src=new URL('food.js?v=20260929-food1',document.currentScript?.src||location.href).href;food.dataset.foodLoader='true';food.onerror=()=>toast('美食模块未能载入，请刷新页面；原行程仍可使用。');document.body.appendChild(food)}
})();
