(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];let timer=null,toastTimer;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),3500)}
function stop(){clearInterval(timer);timer=null;$('#play-route').textContent='播放七日路线';$('#play-route').setAttribute('aria-pressed','false')}
function selectDay(n,manual=true){if(manual)stop();$$('[data-map-day]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.mapDay)===n)));$$('[data-segment]').forEach(p=>{p.classList.toggle('dim',n!==0&&Number(p.dataset.segment)!==n);p.classList.toggle('lit',n!==0&&Number(p.dataset.segment)===n)});$$('[data-flight]').forEach(p=>p.classList.toggle('dim',n!==0&&Number(p.dataset.flight)!==n));const d=$('#day-'+n);$('#route-label').textContent=d?d.dataset.date+' '+$('.day-title p',d).textContent:'汉中往返，自驾与航空双线衔接';$('#route-summary-title').textContent=d?$('.day-title h3',d).textContent:'以额济纳为核心，不把每天排满';$('#route-summary-copy').textContent=d?$('.day-aside .keep',d).textContent:'丹霞、胡杨与沙坡头是三个重点。额济纳连住两晚，最后一晚住中卫，顺路返程。';$('#route-detail').href=d?'#day-'+n:'#itinerary';$('#route-detail').textContent=d?'展开当日安排':'查看完整七日日程';if(window.tripFoodSelect)window.tripFoodSelect(n)}
$$('[data-map-day]').forEach(b=>b.addEventListener('click',()=>selectDay(Number(b.dataset.mapDay))));$('#play-route').addEventListener('click',()=>{if(timer){stop();return}let n=1;selectDay(n,false);$('#play-route').textContent='停止播放';$('#play-route').setAttribute('aria-pressed','true');timer=setInterval(()=>{if(++n>7){stop();return}selectDay(n,false)},1800)});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});document.addEventListener('keydown',e=>{if(e.key==='Escape')stop()});
$('#expand-all').addEventListener('click',()=>$$('.day-card').forEach(d=>d.open=true));$('#collapse-all').addEventListener('click',()=>$$('.day-card').forEach(d=>d.open=false));document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#day-"]');if(a){const d=$(a.getAttribute('href'));if(d)d.open=true}});if(/^#day-[1-7]$/.test(location.hash)){const d=$(location.hash);d.open=true;setTimeout(()=>d.scrollIntoView(),100)}
function fmt(m){m=Math.round(m);let pre='';if(m<0){pre='前一日 ';m=((m%1440)+1440)%1440}return pre+String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
function calculate(){const t=$('#flight-time').value,v=['drive-hours','rest-hours','road-buffer','airport-buffer'].map(id=>Number($('#'+id).value));if(!/^\d{2}:\d{2}$/.test(t)||v.some(x=>!Number.isFinite(x)||x<0)||v[0]<1||v[0]>24||v[1]>8||v[2]>8||v[3]<1||v[3]>6){$('#calc-time').textContent='检查输入';$('#calc-text').textContent='请填写有效起飞时间、1–24小时纯驾驶时间及合理的休息、道路和机场预留。';return}const [h,m]=t.split(':').map(Number),flight=h*60+m,road=v[0]+v[1]+v[2],latest=flight-(road+v[3])*60,arrival=flight-v[3]*60;$('#calc-time').textContent=fmt(latest);$('#calc-text').textContent='按当前假设，建议不晚于'+fmt(latest)+'离开额济纳，预留'+road.toFixed(1)+'小时道路总窗口，并在'+fmt(arrival)+'前抵达机场。'+(latest<360?'这早于06:00初步参考；应提前出发、改选更晚航班或拆分转场，不压缩必要休息。':'06:00是否足够，仍取决于具体酒店—机场导航与实际通行情况。')}
$$('.calc input').forEach(i=>i.addEventListener('input',calculate));calculate();
const key='northwest-autumn-2026-checklist-v1';let stored={},storageOK=true;try{stored=JSON.parse(localStorage.getItem(key)||'{}')||{}}catch(_){storageOK=false}$$('[data-check]').forEach(i=>i.checked=stored[i.dataset.check]===true);
function updateChecks(write=false){const c=$$('[data-check]'),n=c.filter(i=>i.checked).length;$('#check-count').textContent='已准备 '+n+' / '+c.length;$('#check-progress').style.width=n/c.length*100+'%';$('#check-progress-wrap').setAttribute('aria-valuenow',n);if(write)try{localStorage.setItem(key,JSON.stringify(Object.fromEntries(c.map(i=>[i.dataset.check,i.checked]))))}catch(_){storageOK=false}$('#check-local-note').textContent=storageOK?'勾选仅保存在当前浏览器，不上传，也不会与其他设备自动同步。':'当前环境无法持久保存勾选；本次页面内仍可正常使用清单。'}
$$('[data-check]').forEach(i=>i.addEventListener('change',()=>updateChecks(true)));updateChecks();$('#reset-checks').addEventListener('click',()=>{if(!confirm('清空当前浏览器保存的行前准备勾选？'))return;$$('[data-check]').forEach(i=>i.checked=false);updateChecks(true);toast('行前清单已清空')});
function download(text,name,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function markdown(){let s='# 西北秋行｜2026国庆七日自驾总体计划\n\n日期：2026年10月1日至7日。版本：2026-09-29。全部时刻为北京时间。\n\n## 路线与当前状态\n\n汉中 → 武威 → 张掖七彩丹霞 → 嘉峪关 → 额济纳 → 银川 → 中卫沙坡头 → 汉中。\n\n10月2日21:15计划抵达嘉峪关酒泉机场已确认。10月5日银川返京优先21:00–22:00，尤其21:00–21:30；CA1264 21:05–22:55为候选，未确认出票。航天参观待预约，10月3日发射与可参加观礼均未确认。\n\n';$$('.day-card').forEach(d=>{s+='## '+d.dataset.date+' '+d.dataset.weekday+'｜'+$('.day-title h3',d).textContent+'\n\n路线：'+$('.day-title p',d).textContent+'\n\n';$$('.day-badges span',d).forEach(e=>s+=e.textContent+'\n\n');s+=$('.day-intro',d).textContent+'\n\n';$$('.time-slot',d).forEach(e=>{s+='### '+$('time',e).textContent+'｜'+$('h4',e).textContent+'\n\n'+$('p',e).textContent+'\n\n'});$$('.day-aside>div',d).forEach(e=>s+='**'+$('h4',e).textContent+'：**'+$('p',e).textContent+'\n\n');s+='注意：'+$('.day-note',d).textContent+'\n\n';if(window.tripFoodDayMarkdown)s+=window.tripFoodDayMarkdown(Number(d.id.replace('day-','')))});s+='## 返京日时间倒排\n\n最晚出发参考 = 起飞时间 − 实时导航纯驾驶时间 − 途中休息用餐 − 道路额外缓冲 − 机场预留。\n\n示例：21:05起飞，纯驾驶10.5小时、休息1.5小时、道路缓冲1小时、机场预留2.5小时，倒排为05:35离开额济纳。输入不是实时路况；正常休息后仍紧张时应提前或改班，不保证赶机。\n\n## 住宿与预订\n\n武威1晚、嘉峪关1晚、额济纳达来呼布镇2晚、银川1晚、中卫1晚。额济纳连住与返京交通同步核对，随后落实航天参观，再完成其他酒店和票务。\n\n## 行前准备\n\n';$$('.check-row span').forEach(e=>s+='- [ ] '+e.textContent+'\n');s+='\n## 资料与核验边界\n\n[1] Flight.info CA1264公开时刻：https://www.flight.info/CA1264 （查阅2026-09-29，非售票或余票确认）。\n[2] 中国载人航天官方公告：https://www.cmse.gov.cn/gfgg/ （未取得10月3日发射与可参加观礼的确认；公告栏目并非全部商业发射的完整清单）。\n\n所有公路、入住与游览时间为建议预算；票价、天气、景区开放与道路状态须临行复核。\n';if(window.tripFoodMarkdown)s+=window.tripFoodMarkdown();return s}
$('#download-plan').addEventListener('click',()=>{if(!window.tripFoodReady){toast('美食资料仍在加载，请稍后导出；加载失败时刷新页面。');return}download(markdown(),'西北秋行_七日总体计划_2026.md','text/markdown;charset=utf-8');toast('总体计划已导出为Markdown')});
let printStates=[];window.addEventListener('beforeprint',()=>{printStates=$$('.day-card').map(d=>d.open);$$('.day-card').forEach(d=>d.open=true)});window.addEventListener('afterprint',()=>$$('.day-card').forEach((d,i)=>d.open=printStates[i]??true));$('#print-plan').addEventListener('click',()=>window.print());
$('#share').addEventListener('click',async()=>{const url='https://chastelover.github.io/xinjiang-yili-roadtrip/northwest-autumn-2026/';try{if(navigator.share){await navigator.share({title:'西北秋行｜国庆七日旅行手册',text:'河西走廊、额济纳胡杨与沙坡头，7天6晚。',url});return}if(navigator.clipboard&&isSecureContext){await navigator.clipboard.writeText(url);toast('在线网页地址已复制');return}prompt('复制网页地址后分享；离线版可直接分享HTML文件。',url)}catch(e){if(e.name!=='AbortError')prompt('复制以下网页地址分享：',url)}});
if('IntersectionObserver' in window){const o=new IntersectionObserver(entries=>{for(const e of entries){if(!e.isIntersecting)continue;$$('.navlinks a,.mobile-nav a').forEach(a=>{const on=a.getAttribute('href')==='#'+e.target.id;a.classList.toggle('active',on);if(on)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}},{rootMargin:'-12% 0px -68% 0px',threshold:0});$$('main>section[id]').forEach(s=>o.observe(s))}selectDay(0);window.tripExportMarkdown=markdown;
// Keep the base handbook usable even if the optional food module cannot load.
if(!window.tripFoodReady){const food=document.createElement('script');food.src=new URL('food.js?v=20260929-food1',document.currentScript?.src||location.href).href;food.dataset.foodLoader='true';food.onerror=()=>toast('美食模块未能载入，请刷新页面；原行程仍可使用。');document.body.appendChild(food)}
})();
